version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: lottery-system
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"